spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
  datasource:
    url: ${vcap.services.test-db.credentials.jdbcUrl} #jdbc:mysql://localhost:3306/db_troskovi?createDatabaseIfNotExist=true
    username: ${vcap.services.test-db.credentials.username}
    password: ${vcap.services.test-db.credentials.password}
    driver-class-name: com.mysql.jdbc.Driver