spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/db_troskovi?createDatabaseIfNotExist=true
    username: springuser
    password: spring
    driver-class-name: com.mysql.jdbc.Driver